- name: "discord"
  src: "conf/home/.config/discord/settings.json"
  dest: "/home/tie/.config/discord/settings.json"

- name: "tmux config"
  src: "conf/home/.tmux.conf"
  dest: "/home/tie/.tmux.conf"

- name: "zathurarc"
  src: "conf/home/.config/zathura/zathurarc"
  dest: "/home/tie/.config/zathura/zathurarc"
